# DataFrames.jl 介紹 (二): Joins 與 Split-Apply-Combine Strategy

## Day 018 作業1：The Split-Apply-Combine Strategy

同 Day 017，請載入 2020/4/2 COVID-19 Daily Report 資料集，計算每個國家/地區的累計確診人數，並列出所有資料筆數。

In [4]:
using DataFrames, CSV, Statistics

In [2]:
df = CSV.read("04-02-2020.csv")

2569×12 DataFrame. Omitted printing of 8 columns
│ Row  │ FIPS    │ Admin2     │ Province_State │ Country_Region       │
│      │ Int64⍰  │ String⍰    │ String⍰        │ String               │
├──────┼─────────┼────────────┼────────────────┼──────────────────────┤
│ 1    │ 45001   │ Abbeville  │ South Carolina │ US                   │
│ 2    │ 22001   │ Acadia     │ Louisiana      │ US                   │
│ 3    │ 51001   │ Accomack   │ Virginia       │ US                   │
│ 4    │ 16001   │ Ada        │ Idaho          │ US                   │
│ 5    │ 19001   │ Adair      │ Iowa           │ US                   │
│ 6    │ 29001   │ Adair      │ Missouri       │ US                   │
│ 7    │ 40001   │ Adair      │ Oklahoma       │ US                   │
│ 8    │ 8001    │ Adams      │ Colorado       │ US                   │
│ 9    │ 16003   │ Adams      │ Idaho          │ US                   │
│ 10   │ 17001   │ Adams      │ Illinois       │ US                   │
⋮
│ 2559 │ missing │ missing    │ missing        │ Ukraine              │
│ 2560 │ missing │ missing    │ missing        │ United Arab Emirates │
│ 2561 │ missing │ missing    │ missing        │ United Kingdom       │
│ 2562 │ missing │ missing    │ missing        │ Uruguay              │
│ 2563 │ missing │ missing    │ missing        │ Uzbekistan           │
│ 2564 │ missing │ missing    │ missing        │ Venezuela            │
│ 2565 │ missing │ missing    │ missing        │ Vietnam              │
│ 2566 │ missing │ missing    │ missing        │ West Bank and Gaza   │
│ 2567 │ missing │ missing    │ missing        │ Zambia               │
│ 2568 │ missing │ missing    │ missing        │ Zimbabwe             │
│ 2569 │ missing │ unassigned │ Wyoming        │ US                   │

計算計算每個國家/地區的累計確診人數

【提示】可使用 groupby 相關的函式

In [5]:
by(df, :Country_Region, :Confirmed => mean)

181×2 DataFrame
│ Row │ Country_Region       │ Confirmed_mean │
│     │ String               │ Float64        │
├─────┼──────────────────────┼────────────────┤
│ 1   │ US                   │ 105.3          │
│ 2   │ Canada               │ 752.267        │
│ 3   │ United Kingdom       │ 3417.3         │
│ 4   │ China                │ 2497.94        │
│ 5   │ Netherlands          │ 2957.6         │
│ 6   │ Australia            │ 639.5          │
│ 7   │ Denmark              │ 1191.0         │
│ 8   │ France               │ 5992.9         │
│ 9   │ Afghanistan          │ 273.0          │
│ 10  │ Albania              │ 277.0          │
⋮
│ 171 │ Turkey               │ 18135.0        │
│ 172 │ Uganda               │ 45.0           │
│ 173 │ Ukraine              │ 897.0          │
│ 174 │ United Arab Emirates │ 1024.0         │
│ 175 │ Uruguay              │ 350.0          │
│ 176 │ Uzbekistan           │ 205.0          │
│ 177 │ Venezuela            │ 146.0          │
│ 178 │ Vietnam              │ 233.0          │
│ 179 │ West Bank and Gaza   │ 161.0          │
│ 180 │ Zambia               │ 39.0           │
│ 181 │ Zimbabwe             │ 9.0            │

In [7]:
# 顯示所有資料
show(by(df, :Country_Region, :Confirmed => mean), allcols=true, allrows=true)

181×2 DataFrame
│ Row │ Country_Region                   │ Confirmed_mean │
│     │ String                           │ Float64        │
├─────┼──────────────────────────────────┼────────────────┤
│ 1   │ US                               │ 105.3          │
│ 2   │ Canada                           │ 752.267        │
│ 3   │ United Kingdom                   │ 3417.3         │
│ 4   │ China                            │ 2497.94        │
│ 5   │ Netherlands                      │ 2957.6         │
│ 6   │ Australia                        │ 639.5          │
│ 7   │ Denmark                          │ 1191.0         │
│ 8   │ France                           │ 5992.9         │
│ 9   │ Afghanistan                      │ 273.0          │
│ 10  │ Albania                          │ 277.0          │
│ 11  │ Algeria                          │ 986.0          │
│ 12  │ Andorra                          │ 428.0          │
│ 13  │ Angola                           │ 8.0            │
│ 14  │ Antigua and Barbuda              │ 9.0            │
│ 15  │ Argentina                        │ 1133.0         │
│ 16  │ Armenia                          │ 663.0          │
│ 17  │ Austria                          │ 11129.0        │
│ 18  │ Azerbaijan                       │ 400.0          │
│ 19  │ Bahamas                          │ 24.0           │
│ 20  │ Bahrain                          │ 643.0          │
│ 21  │ Bangladesh                       │ 56.0           │
│ 22  │ Barbados                         │ 46.0           │
│ 23  │ Belarus                          │ 304.0          │
│ 24  │ Belgium                          │ 15348.0        │
│ 25  │ Belize                           │ 3.0            │
│ 26  │ Benin                            │ 13.0           │
│ 27  │ Bhutan                           │ 5.0            │
│ 28  │ Bolivia                          │ 123.0          │
│ 29  │ Bosnia and Herzegovina           │ 533.0          │
│ 30  │ Botswana                         │ 4.0            │
│ 31  │ Brazil                           │ 8044.0         │
│ 32  │ Brunei                           │ 133.0          │
│ 33  │ Bulgaria                         │ 457.0          │
│ 34  │ Burkina Faso                     │ 288.0          │
│ 35  │ Burma                            │ 20.0           │
│ 36  │ Burundi                          │ 3.0            │
│ 37  │ Cabo Verde                       │ 6.0            │
│ 38  │ Cambodia                         │ 110.0          │
│ 39  │ Cameroon                         │ 306.0          │
│ 40  │ Central African Republic         │ 3.0            │
│ 41  │ Chad                             │ 8.0            │
│ 42  │ Chile                            │ 3404.0         │
│ 43  │ Colombia                         │ 1161.0         │
│ 44  │ Congo (Brazzaville)              │ 22.0           │
│ 45  │ Congo (Kinshasa)                 │ 134.0          │
│ 46  │ Costa Rica                       │ 396.0          │
│ 47  │ Cote d'Ivoire                    │ 194.0          │
│ 48  │ Croatia                          │ 1011.0         │
│ 49  │ Cuba                             │ 233.0          │
│ 50  │ Cyprus                           │ 356.0          │
│ 51  │ Czechia                          │ 3858.0         │
│ 52  │ Diamond Princess                 │ 712.0          │
│ 53  │ Djibouti                         │ 40.0           │
│ 54  │ Dominica                         │ 12.0           │
│ 55  │ Dominican Republic               │ 1380.0         │
│ 56  │ Ecuador                          │ 3163.0         │
│ 57  │ Egypt                            │ 865.0          │
│ 58  │ El Salvador                      │ 41.0           │
│ 59  │ Equatorial Guinea                │ 15.0           │
│ 60  │ Eritrea                          │ 22.0           │
│ 61  │ Estonia                          │ 858.0          │
│ 62  │ Eswatini                         │ 9.0            │
│ 63  │ Ethiopia                         │ 29.0           │
│ 64  │ Fiji                             │ 7.0            │
│ 65  │ Finland                          │ 1518.0         │
│ 66  │ Gabon                            │ 21.0           │
│ 67  │ Gambia                           │ 4.0            │
│ 68  │ Georgia                          │ 134.0          │
│ 69  │ Germany                          │ 84794.0        │
│ 70  │ Ghana                            │ 204.0          │
│ 71  │ Greece                           │ 1544.0         │
│ 72  │ Grenada                          │ 10.0           │
│ 73  │ Guatemala                        │ 47.0           │
│ 74  │ Guinea                           │ 52.0           │
│ 75  │ Guinea-Bissau                    │ 9.0            │
│ 76  │ Guyana                           │ 19.0           │
│ 77  │ Haiti                            │ 16.0           │
│ 78  │ Holy See                         │ 7.0            │
│ 79  │ Honduras                         │ 219.0          │
│ 80  │ Hungary                          │ 585.0          │
│ 81  │ Iceland                          │ 1319.0         │
│ 82  │ India                            │ 2543.0         │
│ 83  │ Indonesia                        │ 1790.0         │
│ 84  │ Iran                             │ 50468.0        │
│ 85  │ Iraq                             │ 772.0          │
│ 86  │ Ireland                          │ 3849.0         │
│ 87  │ Israel                           │ 6857.0         │
│ 88  │ Italy                            │ 115242.0       │
│ 89  │ Jamaica                          │ 47.0           │
│ 90  │ Japan                            │ 2495.0         │
│ 91  │ Jordan                           │ 299.0          │
│ 92  │ Kazakhstan                       │ 435.0          │
│ 93  │ Kenya                            │ 110.0          │
│ 94  │ Korea, South                     │ 9976.0         │
│ 95  │ Kosovo                           │ 125.0          │
│ 96  │ Kuwait                           │ 342.0          │
│ 97  │ Kyrgyzstan                       │ 116.0          │
│ 98  │ Laos                             │ 10.0           │
│ 99  │ Latvia                           │ 458.0          │
│ 100 │ Lebanon                          │ 494.0          │
│ 101 │ Liberia                          │ 6.0            │
│ 102 │ Libya                            │ 11.0           │
│ 103 │ Liechtenstein                    │ 75.0           │
│ 104 │ Lithuania                        │ 649.0          │
│ 105 │ Luxembourg                       │ 2487.0         │
│ 106 │ MS Zaandam                       │ 9.0            │
│ 107 │ Madagascar                       │ 59.0           │
│ 108 │ Malawi                           │ 3.0            │
│ 109 │ Malaysia                         │ 3116.0         │
│ 110 │ Maldives                         │ 19.0           │
│ 111 │ Mali                             │ 36.0           │
│ 112 │ Malta                            │ 196.0          │
│ 113 │ Mauritania                       │ 6.0            │
│ 114 │ Mauritius                        │ 169.0          │
│ 115 │ Mexico                           │ 1378.0         │
│ 116 │ Moldova                          │ 505.0          │
│ 117 │ Monaco                           │ 60.0           │
│ 118 │ Mongolia                         │ 14.0           │
│ 119 │ Montenegro                       │ 144.0          │
│ 120 │ Morocco                          │ 708.0          │
│ 121 │ Mozambique                       │ 10.0           │
│ 122 │ Namibia                          │ 14.0           │
│ 123 │ Nepal                            │ 6.0            │
│ 124 │ New Zealand                      │ 797.0          │
│ 125 │ Nicaragua                        │ 5.0            │
│ 126 │ Niger                            │ 98.0           │
│ 127 │ Nigeria                          │ 184.0          │
│ 128 │ North Macedonia                  │ 384.0          │
│ 129 │ Norway                           │ 5147.0         │
│ 130 │ Oman                             │ 231.0          │
│ 131 │ Pakistan                         │ 2421.0         │
│ 132 │ Panama                           │ 1317.0         │
│ 133 │ Papua New Guinea                 │ 1.0            │
│ 134 │ Paraguay                         │ 77.0           │
│ 135 │ Peru                             │ 1414.0         │
│ 136 │ Philippines                      │ 2633.0         │
│ 137 │ Poland                           │ 2946.0         │
│ 138 │ Portugal                         │ 9034.0         │
│ 139 │ Qatar                            │ 949.0          │

│ 140 │ Romania                          │ 2738.0         │
│ 141 │ Russia                           │ 3548.0         │
│ 142 │ Rwanda                           │ 84.0           │
│ 143 │ Saint Kitts and Nevis            │ 9.0            │
│ 144 │ Saint Lucia                      │ 13.0           │
│ 145 │ Saint Vincent and the Grenadines │ 2.0            │
│ 146 │ San Marino                       │ 245.0          │
│ 147 │ Saudi Arabia                     │ 1885.0         │
│ 148 │ Senegal                          │ 195.0          │
│ 149 │ Serbia                           │ 1171.0         │
│ 150 │ Seychelles                       │ 10.0           │
│ 151 │ Sierra Leone                     │ 2.0            │
│ 152 │ Singapore                        │ 1049.0         │
│ 153 │ Slovakia                         │ 426.0          │
│ 154 │ Slovenia                         │ 897.0          │
│ 155 │ Somalia                          │ 5.0            │
│ 156 │ South Africa                     │ 1462.0         │
│ 157 │ Spain                            │ 112065.0       │
│ 158 │ Sri Lanka                        │ 151.0          │
│ 159 │ Sudan                            │ 8.0            │
│ 160 │ Suriname                         │ 10.0           │
│ 161 │ Sweden                           │ 5568.0         │
│ 162 │ Switzerland                      │ 18827.0        │
│ 163 │ Syria                            │ 16.0           │
│ 164 │ Taiwan*                          │ 339.0          │
│ 165 │ Tanzania                         │ 20.0           │
│ 166 │ Thailand                         │ 1875.0         │
│ 167 │ Timor-Leste                      │ 1.0            │
│ 168 │ Togo                             │ 39.0           │
│ 169 │ Trinidad and Tobago              │ 94.0           │
│ 170 │ Tunisia                          │ 455.0          │
│ 171 │ Turkey                           │ 18135.0        │
│ 172 │ Uganda                           │ 45.0           │
│ 173 │ Ukraine                          │ 897.0          │
│ 174 │ United Arab Emirates             │ 1024.0         │
│ 175 │ Uruguay                          │ 350.0          │
│ 176 │ Uzbekistan                       │ 205.0          │
│ 177 │ Venezuela                        │ 146.0          │
│ 178 │ Vietnam                          │ 233.0          │
│ 179 │ West Bank and Gaza               │ 161.0          │
│ 180 │ Zambia                           │ 39.0           │
│ 181 │ Zimbabwe                         │ 9.0            │

## 作業2：請列出美國各區域或事件 (依 Province_State 欄) 的累積確診、死亡、康復人數。

【提示】使用 Split-Apply-Combine Strategy 時，有幾種不同的函式可以使用，請參照 `DataFrames.jl` 官方文件 [https://juliadata.github.io/DataFrames.jl/stable/lib/functions/#DataFrames.groupby](https://juliadata.github.io/DataFrames.jl/stable/lib/functions/#DataFrames.groupby)

In [12]:
df2=groupby(df,:Country_Region)

GroupedDataFrame with 181 groups based on key: Country_Region
First Group (2312 rows): Country_Region = "US". Omitted printing of 8 columns
│ Row  │ FIPS    │ Admin2     │ Province_State           │ Country_Region │
│      │ Int64⍰  │ String⍰    │ Union{Missing, String}   │ String         │
├──────┼─────────┼────────────┼──────────────────────────┼────────────────┤
│ 1    │ 45001   │ Abbeville  │ South Carolina           │ US             │
│ 2    │ 22001   │ Acadia     │ Louisiana                │ US             │
│ 3    │ 51001   │ Accomack   │ Virginia                 │ US             │
│ 4    │ 16001   │ Ada        │ Idaho                    │ US             │
│ 5    │ 19001   │ Adair      │ Iowa                     │ US             │
│ 6    │ 29001   │ Adair      │ Missouri                 │ US             │
│ 7    │ 40001   │ Adair      │ Oklahoma                 │ US             │
│ 8    │ 8001    │ Adams      │ Colorado                 │ US             │
│ 9    │ 16003   │ Adams      │ Idaho                    │ US             │
│ 10   │ 17001   │ Adams      │ Illinois                 │ US             │
⋮
│ 2302 │ 6115    │ Yuba       │ California               │ US             │
│ 2303 │ 4027    │ Yuma       │ Arizona                  │ US             │
│ 2304 │ 8125    │ Yuma       │ Colorado                 │ US             │
│ 2305 │ 88888   │ missing    │ Diamond Princess         │ US             │
│ 2306 │ 99999   │ missing    │ Grand Princess           │ US             │
│ 2307 │ 66      │ missing    │ Guam                     │ US             │
│ 2308 │ missing │ missing    │ Northern Mariana Islands │ US             │
│ 2309 │ 72      │ missing    │ Puerto Rico              │ US             │
│ 2310 │ missing │ missing    │ Recovered                │ US             │
│ 2311 │ 78      │ missing    │ Virgin Islands           │ US             │
│ 2312 │ missing │ unassigned │ Wyoming                  │ US             │
⋮
Last Group (1 row): Country_Region = "Zimbabwe". Omitted printing of 8 columns
│ Row │ FIPS    │ Admin2  │ Province_State │ Country_Region │
│     │ Int64⍰  │ String⍰ │ String⍰        │ String         │
├─────┼─────────┼─────────┼────────────────┼────────────────┤
│ 1   │ missing │ missing │ missing        │ Zimbabwe       │

In [16]:
show(by(df2[1],:Province_State , [:Confirmed => mean, :Deaths => mean , :Recovered => mean]), allcols=true, allrows=true)

58×4 DataFrame
│ Row │ Province_State           │ Confirmed_mean │ Deaths_mean │
│     │ Union{Missing, String}   │ Float64        │ Float64     │
├─────┼──────────────────────────┼────────────────┼─────────────┤
│ 1   │ South Carolina           │ 33.7826        │ 0.673913    │
│ 2   │ Louisiana                │ 150.148        │ 5.08197     │
│ 3   │ Virginia                 │ 16.5631        │ 0.398058    │
│ 4   │ Idaho                    │ 25.8667        │ 0.3         │
│ 5   │ Iowa                     │ 9.59375        │ 0.171875    │
│ 6   │ Missouri                 │ 25.0946        │ 0.297297    │
│ 7   │ Oklahoma                 │ 16.3148        │ 0.62963     │
│ 8   │ Colorado                 │ 64.2692        │ 1.53846     │
│ 9   │ Illinois                 │ 124.113        │ 2.62903     │
│ 10  │ Indiana                  │ 36.1667        │ 0.928571    │
│ 11  │ Mississippi              │ 15.0897        │ 0.333333    │
│ 12  │ Nebraska                 │ 9.11111        │ 0.185185    │
│ 13  │ Pennsylvania             │ 117.226        │ 1.45161     │
│ 14  │ Washington               │ 182.543        │ 7.74286     │
│ 15  │ Wisconsin                │ 32.9811        │ 0.716981    │
│ 16  │ Vermont                  │ 26.0           │ 1.30769     │
│ 17  │ Florida                  │ 150.133        │ 2.73333     │
│ 18  │ North Carolina           │ 22.7241        │ 0.241379    │
│ 19  │ California               │ 211.235        │ 4.66667     │
│ 20  │ New York                 │ 1567.9         │ 40.2203     │
│ 21  │ Wyoming                  │ 8.82353        │ 0.0         │
│ 22  │ Michigan                 │ 151.986        │ 5.87324     │
│ 23  │ Maryland                 │ 93.24          │ 1.44        │
│ 24  │ Kentucky                 │ 11.3235        │ 0.455882    │
│ 25  │ Ohio                     │ 39.2027        │ 1.09459     │
│ 26  │ Alaska                   │ 20.4286        │ 0.428571    │
│ 27  │ Kansas                   │ 12.2889        │ 0.266667    │
│ 28  │ Tennessee                │ 32.3295        │ 0.409091    │
│ 29  │ Texas                    │ 34.7192        │ 0.527397    │
│ 30  │ Maine                    │ 26.8571        │ 0.5         │
│ 31  │ Minnesota                │ 13.0175        │ 0.315789    │
│ 32  │ Arizona                  │ 107.188        │ 2.0         │
│ 33  │ Georgia                  │ 37.1389        │ 1.13194     │
│ 34  │ Arkansas                 │ 11.4821        │ 0.214286    │
│ 35  │ New Jersey               │ 1163.18        │ 24.4091     │
│ 36  │ South Dakota             │ 4.85294        │ 0.0588235   │
│ 37  │ Alabama                  │ 19.2656        │ 0.5         │
│ 38  │ West Virginia            │ 7.2            │ 0.0666667   │
│ 39  │ North Dakota             │ 6.11538        │ 0.115385    │
│ 40  │ Massachusetts            │ 640.429        │ 11.0        │
│ 41  │ New Hampshire            │ 35.1111        │ 0.333333    │
│ 42  │ Oregon                   │ 31.7692        │ 0.807692    │
│ 43  │ New Mexico               │ 18.4762        │ 0.285714    │
│ 44  │ Utah                     │ 60.6667        │ 0.388889    │
│ 45  │ Rhode Island             │ 109.5          │ 2.0         │
│ 46  │ Montana                  │ 10.4783        │ 0.26087     │
│ 47  │ Nevada                   │ 146.3          │ 3.8         │
│ 48  │ District of Columbia     │ 653.0          │ 12.0        │
│ 49  │ Connecticut              │ 424.889        │ 12.4444     │
│ 50  │ Hawaii                   │ 51.2           │ 0.2         │
│ 51  │ Delaware                 │ 98.25          │ 3.0         │
│ 52  │ Diamond Princess         │ 49.0           │ 0.0         │
│ 53  │ Grand Princess           │ 103.0          │ 3.0         │
│ 54  │ Guam                     │ 82.0           │ 3.0         │
│ 55  │ Northern Mariana Islands │ 6.0            │ 1.0         │
│ 56  │ Puerto Rico              │ 316.0          │ 12.0        │
│ 57  │ Recovered                │ 0.0            │ 0.0         │
│ 58  │ Virgin Islands           │ 30.0           │ 0.0         │

│ Row │ Recovered_mean │
│     │ Float64        │
├─────┼────────────────┤
│ 1   │ 0.0            │
│ 2   │ 0.0            │
│ 3   │ 0.0            │
│ 4   │ 0.0            │
│ 5   │ 0.0            │
│ 6   │ 0.0            │
│ 7   │ 0.0            │
│ 8   │ 0.0            │
│ 9   │ 0.0            │
│ 10  │ 0.0            │
│ 11  │ 0.0            │
│ 12  │ 0.0            │
│ 13  │ 0.0            │
│ 14  │ 0.0            │
│ 15  │ 0.0            │
│ 16  │ 0.0            │
│ 17  │ 0.0            │
│ 18  │ 0.0            │
│ 19  │ 0.0            │
│ 20  │ 0.0            │
│ 21  │ 0.0            │
│ 22  │ 0.0            │
│ 23  │ 0.0            │
│ 24  │ 0.0            │
│ 25  │ 0.0            │
│ 26  │ 0.0            │
│ 27  │ 0.0            │
│ 28  │ 0.0            │
│ 29  │ 0.0            │
│ 30  │ 0.0            │
│ 31  │ 0.0            │
│ 32  │ 0.0            │
│ 33  │ 0.0            │
│ 34  │ 0.0            │
│ 35  │ 0.0            │
│ 36  │ 0.0            │
│ 37  │ 0.0            │
│ 38  │ 0.0            │
│ 39  │ 0.0            │
│ 40  │ 0.0            │
│ 41  │ 0.0            │
│ 42  │ 0.0            │
│ 43  │ 0.0            │
│ 44  │ 0.0            │
│ 45  │ 0.0            │
│ 46  │ 0.0            │
│ 47  │ 0.0            │
│ 48  │ 0.0            │
│ 49  │ 0.0            │
│ 50  │ 0.0            │
│ 51  │ 0.0            │
│ 52  │ 0.0            │
│ 53  │ 0.0            │
│ 54  │ 0.0            │
│ 55  │ 0.0            │
│ 56  │ 0.0            │
│ 57  │ 9001.0         │
│ 58  │ 0.0            │